import React, { useId } from 'react';

/**
 * Universal Image-based Flower Component
 * Wraps generated botanical assets into the SVG composer.
 * Includes a built-in clipping mask to HIDE the straight stems generated by the AI
 * so they can be seamlessly attached to our sweeping curved layout stems.
 */
export default function ImageFlower({
  type, x = 0, y = 0, scale = 1, rotation = 0, className = '',
  width = 140, height = 140, offsetX = -70, offsetY = -100, 
  clipHeight = 90 // Default crops the bottom part (the straight stem)
}) {
  const uniqueId = useId().replace(/:/g, '');
  const maskId = `clip-${uniqueId}`;
  const filterId = `filter-${uniqueId}`;

  return (
    <g
      transform={`translate(${x}, ${y}) rotate(${rotation}) scale(${scale})`}
      className={`flower flower-${type} ${className}`}
      data-type={type}
      style={{ mixBlendMode: 'multiply' }}
    >
      <defs>
        {/* ALPHA KNOCKOUT FILTER: Targets white/light-gray checkerboard patterns */}
        <filter id={filterId} colorInterpolationFilters="sRGB">
          {/* Isolate Bright pixels. 
              The matrix math is aggressive to kill the light-gray part of the checkerboard.
              Alpha = 8*Alpha - 3*(R+G+B) */}
          <feColorMatrix type="matrix" values="1 0 0 0 0
                                               0 1 0 0 0
                                               0 0 1 0 0
                                               -3 -3 -3 8.8 0" result="knockedOut" />
          
          {/* Step 2: Sharpen the alpha mask and clean up edges */}
          <feComponentTransfer in="knockedOut" result="cleaned">
            <feFuncA type="linear" slope="1.8" intercept="-0.15" />
          </feComponentTransfer>

          {/* Step 3: Recolor/Boost Vibrancy to compensate for alpha loss in highlights */}
          <feComponentTransfer in="cleaned">
            <feFuncR type="gamma" exponent="0.8" amplitude="1.1" />
            <feFuncG type="gamma" exponent="0.8" amplitude="1.1" />
            <feFuncB type="gamma" exponent="0.8" amplitude="1.1" />
          </feComponentTransfer>
          
          <feGaussianBlur stdDeviation="0.3" />
        </filter>

        {/* Soft mask to organically fade out the bottom where the stem gets chopped */}
        <linearGradient id={`${maskId}-fade`} x1="0" x2="0" y1="0" y2="1">
           <stop offset={`${(clipHeight - 20) / height}`} stopColor="white" />
           <stop offset={`${clipHeight / height}`} stopColor="transparent" />
        </linearGradient>
        <mask id={maskId}>
          <rect x={offsetX} y={offsetY} width={width} height={height} fill={`url(#${maskId}-fade)`} />
        </mask>
      </defs>

      <image 
        href={`/flowers/${type}.png`} 
        x={offsetX} 
        y={offsetY} 
        width={width} 
        height={height} 
        mask={`url(#${maskId})`}
        style={{ filter: `url(#${filterId})` }}
      />
    </g>
  );
}
