import React, { useId } from 'react';

/**
 * Universal Image-based Flower Component
 * Wraps generated botanical assets into the SVG composer.
 * Relies on native PNG alpha channels for transparency.
 * Includes a soft gradient mask to hide the straight stems generated by the AI
 * so they can be seamlessly attached to our sweeping curved layout stems.
 */
export default function ImageFlower({
  type, x = 0, y = 0, scale = 1, rotation = 0, className = '',
  width = 140, height = 140, offsetX = -70, offsetY = -100, 
  clipHeight = 140 // Show the entire flower fully, only fade the absolute bottom edge
}) {
  const uniqueId = useId().replace(/:/g, '');
  const maskId = `clip-${uniqueId}`;

  // Gentle fade zone — just 12px to softly blend the bottom edge
  const fadeStart = Math.min((clipHeight - 12) / height, 0.95);
  const fadeEnd = Math.min(clipHeight / height, 1.0);

  return (
    <g
      transform={`translate(${x}, ${y}) rotate(${rotation}) scale(${scale})`}
      className={`flower flower-${type} ${className}`}
      data-type={type}
    >
      <defs>
        {/* Soft gradient mask — only fades the very bottom to hide AI-drawn straight stems */}
        <linearGradient id={`${maskId}-fade`} x1="0" x2="0" y1="0" y2="1">
           <stop offset={`${fadeStart}`} stopColor="white" />
           <stop offset={`${fadeEnd}`} stopColor="black" />
        </linearGradient>
        <mask id={maskId}>
          <rect x={offsetX} y={offsetY} width={width} height={height} fill={`url(#${maskId}-fade)`} />
        </mask>
      </defs>

      {/* White fill behind image to eliminate transparent checkerboard */}
      <rect
        x={offsetX}
        y={offsetY}
        width={width}
        height={height}
        fill="#fffafa"
        mask={`url(#${maskId})`}
      />
      <image 
        href={`/flowers/${type}.png`} 
        x={offsetX} 
        y={offsetY} 
        width={width} 
        height={height} 
        mask={`url(#${maskId})`}
        preserveAspectRatio="xMidYMid meet"
      />
    </g>
  );
}
